### ISSUE TITLE
a working initial viewer that shows the Venetus A scholia and text, with regions of interest

### ISSUE THREAD

**Issue by gregorycrane** [scaife-viewer/beyond-translation-site#100]
https://www.homermultitext.org/facsimiles/venetus-a-2020/pages/urn_cite2_hmt_msA-v1_248v.html -- this is not using IIIF and is a one-off, but it nicely shows the information.

**Comment by gregorycrane** [comment]
![image](https://user-images.githubusercontent.com/5159577/206551519-bcdb2c6f-f8a4-4026-8e0a-3e20076f1833.png)

**Comment by jacobwegner** [comment]
@gregorycrane: Thanks for sharing.

https://www.homermultitext.org/facsimiles/venetus-a-2020/pages/urn_cite2_hmt_msA-v1_12r.html would correspond our view at https://beyond-translation.perseus.org/reader/urn:cts:greekLit:tlg0012.tlg001.msA-folios:12r.1.1-12r.1.25?mode=folio.

@pletcher and I just had a call walking through some of the building blocks within Beyond Translation (specifically the backend where we're loading in some of the CITE data from the CEX files and how we're querying that data for display on the frontend).

To start with, he's going to explore being able to select a text part reference in the viewer and to see the bounding box drawn within OpenSeadragon; there are a few more things we'll need to get sorted out with the scholia data to integrate the regions of interest with the scholia that we'll take on in a later pass.

**Comment by jacobwegner** [comment]
@pletcher and @gregorycrane:  I had a meeting with [Cliff Anderson](https://github.com/CliffordAnderson) (who works at [Jean and Alexander Heard Library at Vanderbilt University](https://github.com/HeardLibrary)), and he was demonstrating some ROI / IIIF functionality that Wikimedia Commons and Wikidata expose.

The Wikidata page for [coronation of Napoleon I](https://www.wikidata.org/wiki/Q973118) refers to a painting ([Jacques-Louis David, The Coronation of Napoleon](https://commons.wikimedia.org/wiki/File:Jacques-Louis_David,_The_Coronation_of_Napoleon_edit.jpg)) that has been tagged with ROIs for the people in the painting.

https://wd-image-positions.toolforge.org/iiif_region/pct:52.6,55,13.4,33.3 has a viewer that draws the ROIs, and the ROIs then link to Wikidata pages (e.g. [Napoleon](https://www.wikidata.org/wiki/Q517)).

I'm not suggesting we incorporate Wikidata or their viewer, but just thought it was another example of interactivity between the image and structured content.

**Comment by jacobwegner** [comment]
PR open at:

https://github.com/scaife-viewer/frontend/pull/65

**Comment by jacobwegner** [comment]
@pletcher and I just talked through the next round of things on a call:

- [ ] @jacobwegner to finish the PR reviews
- [ ] @jacobwegner to ingest the ~20 scholia annotations into the backend so that they are queryable using the `ImageROI` GraphQL field
- [ ] @jacobwegner to leave a few "breadcrumbs" for @pletcher  on token-level highlighting in scaife-viewer/frontend
  - the idea that in a "display mode", we "highlight" in yellow tokens that have rich data available
  - when a user makes a selection on a token, the selected token highlight changes to "green"
  - a user can click on the active selection to de-select it
- [ ] @pletcher will take a pass at allowing a user to select the "form" in the main reader and then highlight the scholia in the folio viewer using the ROI data

If / when all that is working, we can experiment more with bi-directional selection (click a scholia entry to highlight the form), and then other thorny issues (distinguishing between "line" selections and "form" selections, etc)

**Comment by jacobwegner** [comment]
(@jacobwegner would like to also revisit the "commentaries" widget / display mode for scholia...so that selecting a form or scholia entry on the folio viewer would interact with the sidebar widget

**Comment by pletcher** [comment]
Hi @jacobwegner, sorry for taking so long to get back to this. I'm working on the scholia highlights, and I noticed that [textAnnotation ROI](https://beyond-transl-pr-111.herokuapp.com/graphql/#operationName=Scholia&query=query%20Scholia(%24urn%3A%20String!%2C%20%24collectionUrn%3A%20ID)%20%7B%0A%20%20textAnnotations(reference%3A%20%24urn%2C%20collection_Urn%3A%20%24collectionUrn)%20%7B%0A%20%20%20%20edges%20%7B%0A%20%20%20%20%20%20node%20%7B%0A%20%20%20%20%20%20%20%20id%0A%20%20%20%20%20%20%20%20idx%0A%20%20%20%20%20%20%20%20data%0A%20%20%20%20%20%20%20%20urn%0A%20%20%20%20%20%20%20%20roi%20%7B%0A%20%20%20%20%20%20%20%20%20%20urn%0A%20%20%20%20%20%20%20%20%20%20coordinatesValue%0A%20%20%20%20%20%20%20%20%7D%0A%20%20%20%20%20%20%7D%0A%20%20%20%20%7D%0A%20%20%7D%0A%7D%0A&variables=%7B%0A%20%20%22urn%22%3A%22urn%3Acts%3AgreekLit%3Atlg0012.tlg001.msA-folios%3A326v.24.795%22%0A%7D) fields are available at the hosted GraphQL instance, but I can't seem to find the commit where that change happened to test it locally.

I just get an empty array in the `roi` field that I added to ScholiaWidget's gql query.

Do I need to re-ingest some data, or should I be working off of a different branch?

Thanks!

**Comment by jacobwegner** [comment]
(@jacobwegner and @pletcher to sync up on the closed PR; bring new styles forward)

**Comment by jacobwegner** [comment]
@pletcher Would you mind linking to whatever branches your latest is on into this issue, and I can resurrect the PRs / preview instance?

I can then also look at the data mapping task and circle back to you.

Thanks!

**Comment by jacobwegner** [comment]
Preview via:

https://beyond-transl-pr-111.herokuapp.com/reader/urn:cts:greekLit:tlg0012.tlg001.msA-folios:12r.1.1-12r.1.25?mode=folio&entryUrn=urn%3Acite2%3Ascafife-viewer%3Adictionary-entries.atlas_v1%3Alsj-67481

**Comment by jacobwegner** [comment]
Comparing `248v`

https://beyond-transl-pr-111.herokuapp.com/reader/urn:cts:greekLit:tlg0012.tlg001.msA-folios:248v?mode=folio&entryUrn=urn%3Acite2%3Ascafife-viewer%3Adictionary-entries.atlas_v1%3Alsj-67481

https://www.homermultitext.org/facsimiles/venetus-a-2020/pages/urn_cite2_hmt_msA-v1_248v.html

cc @gregorycrane

**Comment by jacobwegner** [comment]
Getting very close to these changes being merged.

A few final TODOS:
- [ ] Figure out if we can get a data update done easily (https://github.com/scaife-viewer/beyond-translation-site/issues/100#issuecomment-1697481630)
- [ ] Distinguish between "Scholia" and "Commentary/Textual Notes" so the widgets don't duplicate content
<img width="1262" alt="image" src="https://github.com/scaife-viewer/beyond-translation-site/assets/629062/8ed482d8-0c50-423c-a2c2-e87e35b3ad0e">

**Comment by jacobwegner** [comment]
@gregorycrane latest data and code have been deployed here:

https://beyond-transl-pr-111.herokuapp.com/reader/urn:cts:greekLit:tlg0012.tlg001.msA-folios:12r.1.1-12r.1.25?mode=folio

<img width="1525" alt="image" src="https://github.com/scaife-viewer/beyond-translation-site/assets/629062/41d567bf-b686-4bfb-8615-0e1a856abf48">

<img width="936" alt="image" src="https://github.com/scaife-viewer/beyond-translation-site/assets/629062/271bbb7c-6b5a-4bb2-8ccb-8d4e5a1a5ada">

<img width="936" alt="image" src="https://github.com/scaife-viewer/beyond-translation-site/assets/629062/6c65d34a-9a74-4490-b810-87b4a20f070f">

<img width="1508" alt="image" src="https://github.com/scaife-viewer/beyond-translation-site/assets/629062/d67cce3d-d6de-4908-b666-4dfd8ff6f79f">

I still have a couple of small housekeeping tasks, but I think at this point I'd like you to take a look and see if what we have done is "good enough".

**Comment by jacobwegner** [comment]
I discovered we had been missing several folios:

<img width="696" alt="image" src="https://github.com/scaife-viewer/beyond-translation-site/assets/629062/7a663792-28e1-4f9c-a80b-9fb66d6ebc7a">

`294v-310r`

vs https://beyond-transl-pr-111.herokuapp.com/reader/urn:cts:greekLit:tlg0012.tlg001.msA-folios:294r?toc=urn%3Acite%3Ascaife-viewer%3Atoc.iliad-folio-ref-22&mode=folio

<img width="696" alt="image" src="https://github.com/scaife-viewer/beyond-translation-site/assets/629062/1c3f3287-2c6f-4d01-b989-537af1882c2d">

**Comment by jacobwegner** [comment]
Last bits of feedback from @gregorycrane:

- [ ] Adding labels / colors to the different kinds of scholia
- [ ] Investigate "bounds" checking for OpenSeaDragon zooming (full-screen behavior within the "split-pane" viewer)

**Comment by jacobwegner** [comment]
Have to step away for the day, but I did find a few OpenSeaDragon settings to fix the zoom issues, and I've been able to replicate some of the border styling from HMT:

_Scaife Viewer_:

![image](https://github.com/scaife-viewer/beyond-translation-site/assets/629062/a5a782c6-4b26-498f-806b-e4997d1f7f93)

_HMT_:

![image](https://github.com/scaife-viewer/beyond-translation-site/assets/629062/e04f8b2e-1e55-49fb-90b4-03ec8acf25dc)

**Comment by jacobwegner** [comment]
Scholia entries in the sidebar now show the same colors as the viewer:

<img width="1080" alt="image" src="https://github.com/scaife-viewer/beyond-translation-site/assets/629062/458c2199-dc2f-4fd7-b837-79177449b32b">

and we have a legend that shows what type of scholia correspond to each color:

<img width="672" alt="image" src="https://github.com/scaife-viewer/beyond-translation-site/assets/629062/20e92741-fdf0-4ee9-881f-abe309d1dd6f">

**Comment by jacobwegner** [comment]
@gregorycrane I have made all of the changes we discussed on Tuesday.  I'm going to move on to UD stuff next week, but I am still waiting a final look from you before we merge / deploy to production:

https://beyond-transl-pr-111.herokuapp.com/reader/urn:cts:greekLit:tlg0012.tlg001.msA-folios:12r.1.1-12r.1.25?mode=folio

<img width="1564" alt="image" src="https://github.com/scaife-viewer/beyond-translation-site/assets/629062/31e95044-8a3a-4bf2-a923-a3824e5d8eb2">

**Comment by jacobwegner** [comment]
@gregorycrane The latest changes to the Legend and showing Scholia kind on hover have been deployed to the preview instance:

https://beyond-transl-pr-111.herokuapp.com/reader/urn:cts:greekLit:tlg0012.tlg001.msA-folios:12r.1.1-12r.1.25?mode=folio

<img width="1378" alt="image" src="https://github.com/scaife-viewer/beyond-translation-site/assets/629062/ed600628-6e14-4dd1-8b8c-b04dc7a6c991">

I'm going to cut a production release and will close this issue when that has been completed.

**Comment by jacobwegner** [comment]
@gregorycrane This has been deployed in the [v2023-11-07-001](https://github.com/scaife-viewer/beyond-translation-site/releases/tag/v2023-11-07-001) release:

https://beyond-translation.perseus.org/reader/urn:cts:greekLit:tlg0012.tlg001.msA-folios:12r.1.1-12r.1.25?mode=folio&rs=image
