### ISSUE TITLE
odd formatting of Treebank page: https://beyond-translation-gagdt-dev.herokuapp.com/reader/urn:cts:greekLit:tlg0012.tlg002.perseus-grc2:5.1-5.10?mode=syntax-trees

### ISSUE THREAD

**Issue by gregorycrane** [scaife-viewer/beyond-translation-site#27]
A small but important point: I can't get the whole poetic line on a single visual line in https://beyond-translation-gagdt-dev.herokuapp.com/reader/urn:cts:greekLit:tlg0012.tlg002.perseus-grc2:5.1-5.10?mode=syntax-trees

I hide the right and left widget bars but the formatting does not take advantage of the extra space. This is important for readability.

**Comment by jacobwegner** [comment]
@gregorycrane: There are a couple of things we might consider doing (cc @jtauber), but in the immediate, if you set "Text Width" to "Full", that _will_ take advantage of the extra space:

<img width="1165" alt="image" src="https://user-images.githubusercontent.com/629062/140976461-3fa6be73-8166-484d-a7d2-999c029c2430.png">

@jtauber Thoughts on the following?

- [ ] Minimize sidebars in syntax tree display mode (like we already do for the alignments mode):
_alignments_:
<img width="1165" alt="image" src="https://user-images.githubusercontent.com/629062/140976627-1c69590b-be2d-4111-93e9-2e3f1b123e84.png">

_syntax trees_:
<img width="1165" alt="image" src="https://user-images.githubusercontent.com/629062/140976637-798c4bfd-27a7-475a-a0c6-652331d7b0cc.png">

- [ ] Toggle to "Full" width when entering the syntax tree display mode (and toggle back to "Normal" when returning to "Default" display mode)

**Comment by jacobwegner** [comment]
@gregorycrane: I made the above changes and have deployed them:

https://beyond-translation-gagdt-dev.herokuapp.com/reader/urn:cts:greekLit:tlg0012.tlg002.perseus-grc2:5.1-5.10?mode=syntax-trees
