### ISSUE TITLE
short defs seem to ignore accents -- in Il. 1.1: we get 'a seeing' [=θέα] instead of a 'goddess' for θέα

### ISSUE THREAD

**Issue by gregorycrane** [scaife-viewer/beyond-translation-site#43]
Ignoring accents has its down sides.

https://beyond-translation-gagdt-dev.herokuapp.com/reader/urn:cts:greekLit:tlg0012.tlg001.perseus-grc2:1.1-1.7?mode=syntax-trees

Lenny Muellner saw the mistake immediately --

**Comment by jacobwegner** [comment]
Capturing a few subtasks...
- [ ] take a second pass at linking short defs and lemmas at ingestion (may get a second look from @jtauber )
- [ ] Change queries on FE / BE
- [ ] When ambiguous show multiple matches

**Comment by jacobwegner** [comment]
Re:
> When ambiguous show multiple matches

```
# Interlinear
Token: Πηληϊάδεω
Lemma: Πηληιάδης

# Treebank
Token: Πηληϊάδεω
Lemma: Πηλείδης

# Cunliffe
Headwords: Πηληϊάδης, Πηληιάδης
```
Loegion has an interesting form of healing:

<img width="1328" alt="image" src="https://user-images.githubusercontent.com/629062/154359970-56291ae9-43c0-47af-88d3-d6a1f8b984fd.png">

The dictionary entries backend does something similar:

https://tinyurl.com/peleiades-gql

<img width="778" alt="image" src="https://user-images.githubusercontent.com/629062/154361027-ba3b91b8-0d70-48f4-a763-b202358d6e25.png">

But we don't yet _show_ anything

**Comment by jacobwegner** [comment]
Also interesting:

https://logeion.uchicago.edu/%CE%A0%CE%B7%CE%BB%CE%B7%CF%8A%CE%AC%CE%B4%CE%B7%CF%82

vs.

https://logeion.uchicago.edu/%CE%A0%CE%B7%CE%BB%CE%B7%CE%B9%CE%AC%CE%B4%CE%B7%CF%82
