### ISSUE TITLE
generalizing dictionary support

### ISSUE THREAD

**Issue by gregorycrane** [scaife-viewer/beyond-translation-site#44]
We need to be able to show multiple lexica. In this case:
* Cunliffe
* LSJ (https://github.com/PerseusDL/lexica/tree/master/CTS_XML_TEI/perseus/pdllex)
* Autenrieth ([github.com/gregorycrane/Homerica](https://github.com/gregorycrane/Homerica/blob/4ffd856b5cec1afbe6ceb3b304226e56db82c198/autenrieth.xml))
* Cambridge Greek Lexicon (@jtauber)
How do we deal with the display and user choice?

**Comment by jacobwegner** [comment]
- Identify existing dictionaries
- Ingest LSJ
- Attributions

**Comment by jacobwegner** [comment]
Have laid the groundwork for attributions / handling duplicate entries, but need to:

- [ ] Ingest LSJ's nested senses
- [ ] Handle the "block" entry for LSJ when senses aren't present

**Comment by jacobwegner** [comment]
Have done a first pass at ingesting entries from LSJ; `μῆνις` and `ἀείδω` were chosen for overlap with Il. 1.1:

_Entries grouped by headword_:

<img src="https://user-images.githubusercontent.com/629062/161748612-b0ce5ac1-c33e-4066-9b64-94565aa7225e.png" width=400 />

_Cunliffe_:
<img src="https://user-images.githubusercontent.com/629062/161748665-ec8c33be-7033-4a17-9920-8f4c21831c16.png" width=400 />

_LSJ_:
<img src="https://user-images.githubusercontent.com/629062/161748694-2a0e9e2d-798e-44c1-8a76-7fd7e123a30f.png" width=400 />

**Comment by jacobwegner** [comment]
I've created #62 and #63 to track adding these additional dictionaries.  I'll likely add additional issues and use this issue as a sort of "epic".
