### ISSUE TITLE
Add the ability to browse to other instances of a lemma in a given text

### ISSUE THREAD

**Issue by jacobwegner** [scaife-viewer/beyond-translation-site#48]
(_aka, the lemma traversal widget_)

Similar to what is possible on [vocab.perseus.org](https://vocab.perseus.org/lemma/53534/?filter=urn:cts:greekLit:tlg0012.tlg001.perseus-grc2):

<img width="465" alt="image" src="https://user-images.githubusercontent.com/629062/154356261-4099860a-00be-4d06-a181-da148d9d5092.png">

## Acceptance Criteria

- [ ] Query for other occurrences when a lemma is selected
- [ ] Work similar to the dictionary entry widget (update URN but keep other display attrs in place)

## Developer Notes

Have started some WIP queries locally; need to think through performance as number of lemmas grow.

**Comment by jacobwegner** [comment]
(There might be some reusable bits with something like the table of contents widget, with the difference being that we generate the TOC on-demand rather than at ingestion time)

**Comment by jacobwegner** [comment]
@gregorycrane I have a first pass of this done.

1) Browse to https://beyond-translation-gagdt-dev.herokuapp.com/reader/urn:cts:greekLit:tlg0012.tlg001.perseus-grc2:5.34?mode=syntax-trees&entryUrn=urn%3Acite2%3AexploreHomer%3Aentries.atlas_v1%3A1.6424
2) Click `μῆνιν` in `5.34`
3) Scroll down to the "Passages With Lemma" widget

![image](https://user-images.githubusercontent.com/629062/155012883-a14753c2-5d94-4e0f-8561-0904e694e819.png)

4) Click `1.1` in the widget to navigate to `1.1`;

![image](https://user-images.githubusercontent.com/629062/155012883-a14753c2-5d94-4e0f-8561-0904e694e819.png)

5) Navigate to other occurrences

**Comment by gregorycrane** [comment]
This is really really good!

A useful addition -- hopefully easy: include the form as well as the citation.
You get the citation from the record that also have the form in it. You have space to print the form next to each citation  -- a big help.

So the record for mhnin in Il. 5.34 is:

~~~
<word id="29" form="μῆνιν" lemma="μῆνις" postag="n-s---fa-" head="28" relation="OBJ" cite="urn:cts:greekLit:tlg0012.tlg001:5.34"/>
~~~

Print:

~~~
5.34 μῆνιν
~~~

**Comment by gregorycrane** [comment]
This display allowed me immediately to see an error in the lemmatization

ἀλεώμεθα does not mean "grind"  and come from ἀλέω. It comes from ἀλέομαι, "to escape"

![image](https://user-images.githubusercontent.com/5159577/155154785-863d77e3-3517-4914-ad61-a39abac1628a.png)

**Comment by jacobwegner** [comment]
I'll be deploying the changes we talked about (adding `form` and `postag`) later this afternoon:

![image](https://user-images.githubusercontent.com/629062/155194959-6ade49b4-13d6-406a-a97e-e1a98f7f00ad.png)

**Comment by gregorycrane** [comment]
Now THAT is EVEN more awesome! This is great!

**Comment by jacobwegner** [comment]
We'll iterate using https://github.com/scaife-viewer/beyond-translation-site/issues/56
