### ISSUE TITLE
Treebank image cut off

### ISSUE THREAD

**Issue by gregorycrane** [scaife-viewer/beyond-translation-site#50]
The image of this treebank cuts out on the right prematurely -- like there was a limit to the x-axis side.
https://beyond-translation-gagdt-dev.herokuapp.com/reader/urn:cts:greekLit:tlg0012.tlg001.perseus-grc2:16.623?mode=syntax-trees&entryUrn=urn%3Acite2%3AexploreHomer%3Aentries.atlas_v1%3A1.1673&rs
![image](https://user-images.githubusercontent.com/5159577/155247911-0853875b-dfa7-4009-9172-c42f1d59bc21.png)

**Comment by jacobwegner** [comment]
There have been quite a few things we've had to fight through with the underlying library we're using to render the trees.

For this particular tree, if you're on a smaller display, you can toggle the sidebars open / shut and that should help prevent text from being clipped:

<img width="919" alt="image" src="https://user-images.githubusercontent.com/629062/155425255-8791128b-68f1-4195-aa5a-90445a460970.png">

<img width="919" alt="image" src="https://user-images.githubusercontent.com/629062/155425267-d10a07be-41b8-41fd-bde6-29f022dc3dca.png">

It is less of an issue on larger displays:

<img width="1727" alt="image" src="https://user-images.githubusercontent.com/629062/155425341-88a74bdb-5438-4b1e-a289-d9adc32e7791.png">

I'll try and circle back to see if there is anything else we can do to help, but it might be a limitation that requries us to choose a different rendering library.

**Comment by jacobwegner** [comment]
@gregorycrane I fought with the library again...should no longer clip:

https://beyond-translation-gagdt-dev.herokuapp.com/reader/urn:cts:greekLit:tlg0012.tlg001.perseus-grc2:16.623?mode=syntax-trees&entryUrn=urn%3Acite2%3AexploreHomer%3Aentries.atlas_v1%3A1.1673&rs

**Comment by jacobwegner** [comment]
I'll consider this closed
