### ISSUE TITLE
IIIF alignment not implemented here

### ISSUE THREAD

**Issue by gregorycrane** [scaife-viewer/beyond-translation-site#6]
The following does not work: https://beyond-translation.perseus.org/reader/urn:cts:greekLit:tlg0012.tlg001.msA-folios:12r.1.1-12r.1.25?mode=folio

we get neither the transcription nor the IIIF image.

This functions at the explore homer site:
https://explorehomer-dev.scaife-viewer.org/reader/urn:cts:greekLit:tlg0012.tlg001.msA-folios:12r.1.1-12r.1.25?mode=folio

**Comment by jacobwegner** [comment]
Resolved via 3e48b47b1f15eaa3124fc1ad907d774eed33f0f5 and deployed:

https://beyond-translation.perseus.org/reader/urn:cts:greekLit:tlg0012.tlg001.msA-folios:12r.1.1-12r.1.25?mode=folio
