### ISSUE TITLE
audio from explore homer not yet installed here

### ISSUE THREAD

**Issue by gregorycrane** [scaife-viewer/beyond-translation-site#7]
We need the audio that is enabled on https://explorehomer-dev.scaife-viewer.org/reader/urn:cts:greekLit:tlg0012.tlg001.perseus-grc2:1.1-1.7

Obviously, we need to generalize that function and allow others to add audio but the Chamberlain recording makes the point -- and is instantly useful in class.

**Comment by jacobwegner** [comment]
Resolved via 933a5fa6c998abcaa651533cbdbd60b188394dcf and deployed to the site:

https://beyond-translation.perseus.org/reader/urn:cts:greekLit:tlg0012.tlg001.perseus-grc2:1.1-1.7
