### ISSUE TITLE
Allow user to specify a dictionary when viewing a passage in dictionary entries display mode

### ISSUE THREAD

**Issue by gregorycrane** [scaife-viewer/beyond-translation-site#71]
https://beyond-translation-gagdt-dev.herokuapp.com/reader/urn:cts:greekLit:tlg0012.tlg001.perseus-grc2:9.156?entryUrn=urn%3Acite2%3Ascafife-viewer%3Adictionary-entries.atlas_v1%3Alsj-108083&mode=dictionary-entries

Does dictionary mode adapt to the coverage of the currently selected dictionary?

**Comment by jacobwegner** [comment]
(was _Does "dictionary mode" know which dictionary is open?_)

**Comment by jacobwegner** [comment]
This has been released to production via [v2022-05-18-001](https://github.com/scaife-viewer/beyond-translation-site/releases/tag/v2022-05-18-001)
